### ISSUE TITLE
Message queuing doesn't work when destination is window or frame(s) 

### ISSUE THREAD

**Issue by zikaari** [zikaari/crx-bridge#1]
If `content-script` or `devtools` are not ready (loaded), messages sent to them get queued up and get delivered when ready.

This does not happen when destination is something like `devtools:frame` or `window`, since getting to these is accomplished using `window.postMessage` and not chrome ports.

**Comment by gabicasas** [comment]
> If `content-script` or `devtools` are not ready (loaded), messages sent to them get queued up and get delivered when ready.
> 
> This does not happen when destination is something like `devtools:frame` or `window`, since getting to these is accomplished using `window.postMessage` and not chrome ports.

I don´t understand very well.
How can I fix this problem?

**Comment by zikaari** [comment]
Working nominally in the upcoming release - https://github.com/antfu/webext-bridge/pull/24
