### ISSUE TITLE
Error: This script should only be loaded in a browser extension. when importing bridge in the window context

### ISSUE THREAD

**Issue by dmaretskyi** [zikaari/crx-bridge#7]
Error: This script should only be loaded in a browser extension.

Errors is thrown from `webextension-polyfill` when trying to import bridge in the window context.

Using Chrome Version 86.0.4240.111

**Comment by NeekSandhu** [comment]
The very thing that I skip testing, is the thing that fails. Will separate the window context messaging hooks into a separate file. How blocked are you?

**Comment by Marik-D** [comment]
I'm currently using version 2, it's working perfectly for us

**Comment by pakholeung37** [comment]
window(like inject script) still can not call Bridge.setNamespace.

**Comment by NeekSandhu** [comment]
For now can you guys try using version `2.2.0` of this package? I'll work on a fix in the meantime.

**Comment by zikaari** [comment]
Fixed in https://github.com/antfu/webext-bridge/pull/24

Please help us expedite the merge and release by reviewing the PR and testing the code locally on your system to make sure it's all good.

**Comment by zikaari** [comment]
Fixed as part of `webext-bridge@6.0.0`
